server:
  port: 8091
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ll-music?allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true

project:
  folder: C:/music_project/file_web_app

log:
  root:
    level: debug

admin:
  account: admin
  password: admin123

oss:
  endpoint: oss-cn-beijing.aliyuncs.com
  bucket: wangjinmusic
  accessKeyId: ${OSS_ACCESS_KEY_ID:}
  accessKeySecret: ${OSS_ACCESS_KEY_SECRET:}


